const { Configuration, OpenAIApi } = require("openai");

// Configure the OpenAI API with your API key
const configuration = new Configuration({
  apiKey: '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',
});

// Create an instance of the OpenAI API
const openai = new OpenAIApi(configuration);

/**
 * Function to interact with the OpenAI API and generate a response to a given question.
 * @param {string} question - The user's question.
 * @returns {Promise<string>} - The response generated by the OpenAI API.
 */
const checkIt = async (question) => {
  let messages = [
    { role: 'user', content: question }
  ];
  try {
    // Create a chat completion using the GPT model
    const completion = await openai.createChatCompletion({
      model: 'gpt-3.5-turbo',
      messages
    });

    // Extract the response from the completion and convert it to a JSON string
    const jsonString = JSON.stringify(completion.data.choices[0].message.content);

    // Return the response
    return jsonString;
  } catch (error) {
    if (error.response) {
      console.error(error.response.status, error.response.data);
    } else {
      console.error(`Error with OpenAI API request: ${error.message}`);
    }
  }
}

// Export the checkIt function to be used in other modules
module.exports = { checkIt };
